import fs from "fs/promises";
import { existsSync } from "fs";
import path from "path";
import { db, schema } from "@/db/client";
import { eq } from "drizzle-orm";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const REPO_ROOT = path.resolve(process.cwd(), "..");
const DEMOS_DIR = path.join(REPO_ROOT, "demos");

type DemoConfig = {
  company: { name: string; logo: string | null; primaryColor: string; location: string };
  workflow: {
    primary: string;
    enabled: string[];
    runnerLabels?: Record<string, { label?: string; detail?: string }>;
  };
  scale: { units: number; properties: number; monthlyHoursBefore: number };
  details: {
    utilities?: string[];
    propertyManagementSystem?: string;
    quotedPainPoint?: string;
    painNarrative?: string;
    howItWorks?: string[];
    mathBreakdown?: {
      statementsPerMonth?: number;
      hoursAfter?: number;
      manualEquivalentHours?: number;
    };
  };
};

async function readConfig(slug: string): Promise<DemoConfig> {
  const dataPath = path.join(DEMOS_DIR, slug, "config", "demo.data.json");
  const tsPath = path.join(DEMOS_DIR, slug, "config", "demo.config.ts");

  if (existsSync(dataPath)) {
    const raw = await fs.readFile(dataPath, "utf-8");
    return JSON.parse(raw) as DemoConfig;
  }

  // Fallback: extract the object literal from the TS file (we always write it
  // with JSON.stringify so the literal IS valid JSON between `= ` and the final `;`).
  const ts = await fs.readFile(tsPath, "utf-8");
  const match = ts.match(/export const demoConfig: DemoConfig = ([\s\S]+?);\s*$/m);
  if (!match) throw new Error(`Couldn't parse demoConfig in ${tsPath}`);
  return JSON.parse(match[1]) as DemoConfig;
}

function configToSource(companyName: string, config: DemoConfig): string {
  return `/**
 * Personalized demo config for ${companyName}.
 * Generated by outreach_hub. Edit demo_templates/property_management to change the template;
 * edit this file to tweak per-prospect details.
 */

export type WorkflowKey =
  | "utility_billing"
  | "maintenance"
  | "vendors"
  | "ap_processing";

export type RunnerStageKey = "connect" | "scrape" | "parse" | "match" | "post";

export interface RunnerStageLabel {
  label?: string;
  detail?: string;
}

export interface DemoConfig {
  company: {
    name: string;
    logo: string | null;
    primaryColor: string;
    location: string;
  };
  workflow: {
    primary: WorkflowKey;
    enabled: WorkflowKey[];
    runnerLabels?: Partial<Record<RunnerStageKey, RunnerStageLabel>>;
  };
  scale: {
    units: number;
    properties: number;
    monthlyHoursBefore: number;
  };
  details: {
    utilities?: string[];
    propertyManagementSystem?: string;
    quotedPainPoint?: string;
    painNarrative?: string;
    howItWorks?: string[];
    mathBreakdown?: {
      statementsPerMonth?: number;
      hoursAfter?: number;
      manualEquivalentHours?: number;
    };
  };
}

export const demoConfig: DemoConfig = ${JSON.stringify(config, null, 2)};
`;
}

async function writeConfig(slug: string, config: DemoConfig) {
  const dir = path.join(DEMOS_DIR, slug, "config");
  await fs.writeFile(path.join(dir, "demo.data.json"), JSON.stringify(config, null, 2));
  await fs.writeFile(path.join(dir, "demo.config.ts"), configToSource(config.company.name, config));
}

export async function GET(_req: Request, { params }: { params: { slug: string } }) {
  try {
    const config = await readConfig(params.slug);
    return new Response(JSON.stringify(config), {
      headers: { "Content-Type": "application/json" },
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    return new Response(JSON.stringify({ error: message }), {
      status: 404,
      headers: { "Content-Type": "application/json" },
    });
  }
}

type PatchPayload = {
  company?: { name?: string; primaryColor?: string; location?: string };
  details?: {
    painNarrative?: string;
    howItWorks?: string[];
  };
};

export async function PUT(req: Request, { params }: { params: { slug: string } }) {
  const slug = params.slug;
  const demoDir = path.join(DEMOS_DIR, slug);
  if (!existsSync(demoDir)) {
    return new Response(JSON.stringify({ error: `No demo at demos/${slug}` }), {
      status: 404,
      headers: { "Content-Type": "application/json" },
    });
  }

  let patch: PatchPayload;
  try {
    patch = (await req.json()) as PatchPayload;
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON body" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const config = await readConfig(slug);

  // Shallow-merge only the editable fields. Don't touch workflow / scale / runnerLabels.
  if (patch.company) {
    if (typeof patch.company.name === "string") config.company.name = patch.company.name;
    if (typeof patch.company.primaryColor === "string")
      config.company.primaryColor = patch.company.primaryColor;
    if (typeof patch.company.location === "string") config.company.location = patch.company.location;
  }
  if (patch.details) {
    if (typeof patch.details.painNarrative === "string")
      config.details.painNarrative = patch.details.painNarrative;
    if (Array.isArray(patch.details.howItWorks))
      config.details.howItWorks = patch.details.howItWorks;
  }

  await writeConfig(slug, config);

  // Mirror name/location changes back to the DB so the prospect list stays in sync.
  if (patch.company?.name || patch.company?.location) {
    const today = new Date().toISOString().slice(0, 10);
    db.update(schema.prospects)
      .set({
        ...(patch.company.name ? { company: patch.company.name } : {}),
        ...(patch.company.location ? { location: patch.company.location } : {}),
        lastTouch: today,
      })
      .where(eq(schema.prospects.slug, slug))
      .run();
  }

  return new Response(JSON.stringify(config), {
    headers: { "Content-Type": "application/json" },
  });
}
